# Generated by Django 4.1.5 on 2023-01-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='Категория')),
                ('descriptions_category', models.CharField(max_length=300, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название')),
                ('descriptions', models.CharField(max_length=300, verbose_name='Описание')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Изображение')),
                ('category', models.IntegerField(verbose_name='Категория')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date_created', models.DateTimeField(verbose_name='Дата создания')),
                ('date_of_change', models.DateTimeField(verbose_name='Дата изменения')),
                ('cat_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
            ],
        ),
    ]
