# Generated by Django 4.1.5 on 2023-02-06 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='URL')),
                ('content', models.CharField(max_length=600, verbose_name='содержимое')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Изображение')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('publication_status', models.CharField(choices=[('active', 'активно'), ('moderation', 'модерация')], default='moderation', max_length=15, verbose_name='признак публикации')),
                ('number_of_views', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='Категория')),
                ('descriptions_category', models.CharField(max_length=300, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название')),
                ('descriptions', models.CharField(max_length=300, verbose_name='Описание')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date_created', models.DateTimeField(verbose_name='Дата создания')),
                ('date_of_change', models.DateTimeField(verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='Номер')),
                ('version_name', models.CharField(max_length=35, verbose_name='Название')),
                ('sign', models.CharField(choices=[('active', 'активная'), ('outdated', 'устаревшая')], default='active', max_length=15, verbose_name='Признак')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
