# Generated by Django 4.1.5 on 2023-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='URL')),
                ('content', models.CharField(max_length=600, verbose_name='содержимое')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Изображение')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('publication_status', models.CharField(choices=[('active', 'активно'), ('moderation', 'модерация')], default='moderation', max_length=15, verbose_name='признак публикации')),
                ('number_of_views', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
            },
        ),
    ]
