# Generated by Django 4.1.5 on 2023-02-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('change_status', 'Can change the status'), ('change_descriptions_product', 'Can change the description of products'), ('change_category_in_product', 'Can change the product category')]},
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(True, 'активно'), (False, 'модерация')], default=False, verbose_name='Статус отображения'),
        ),
    ]
